### ISSUE TITLE
Difference with reference paper

### ISSUE THREAD

**Issue by NicolayP** [ICL-SML/pilco-matlab#1]
Hello, 
I'm trying to reimplement your work but I'm a bit confused with the math involved in the moment matching algorithm. To compute the different q_a, equation (15), the denominator of the constant factor is set to Sigma*Lengthscale^-1 + I. However in the implementation it is set to Lengthscale^-1 * Sigma * Lengthscale^-1 + I, see the code section.

https://github.com/ICL-SML/pilco-matlab/blob/a0b48b7831911837d060617903c76c22e4180d0b/gp/gp0.m#L70

I don't know if this is a mistake or if there is something I'm missing.

Regards

**Comment by mpd37** [comment]
In the paper, the matrix contains the *squared* length-scales. In the code, iL has the non-squared lengths-scales, so that iL * iL = \lambda^{-1}. 

Does this help?

**Comment by NicolayP** [comment]
Thank you. I was a bit confused but this definitely helps.
